### ISSUE TITLE
Go get command

### ISSUE THREAD

**Issue by smhmd** [a1phat0ny/torrodle#3]
From README:
`$ go get github.com/a1phat0ny/torrodle/cmd/...`

The command is eclipsed. What's the right command? 
```fish
$ go get github.com/a1phat0ny/torrodle || go get github.com/a1phat0ny/torrodle/cmd/torrodle/main.go
``` 
this didn't work.

(An aside: Can I force `go get` to use `--depth 1` when cloning a git repo?)

**Comment by a1phat0ny** [comment]
1. `go get github.com/a1phat0ny/torrodle/cmd/torrodle/main.go` is wrong.
2. `go get github.com/a1phat0ny/torrodle` is correct only if you want to use `torrodle` as a library instead of a command-line program.

> `go get github.com/a1phat0ny/torrodle/cmd/...` is a bit different from `go get github.com/a1phat0ny/torrodle` though. The uneclipsed command saves the package to your `$GOPATH` whereas the eclipsed command saves the package **and** installs all available binaries of all the main packages inside the `cmd` package.

If you are going to use `torrodle` as a command-line program (which I guess is your current situation), use `go get github.com/a1phat0ny/torrodle/cmd/...` to install the `torrodle` binary to `$GOPATH/bin`.
If it doesn't work, then I guess probably `$GOPATH/bin` isn't in your `$PATH` since the above two commands will install the `torrodle` binary to `$GOPATH/bin`.

(If you are going to use `torrodle` as a Go library, use `go get github.com/a1phat0ny/torrodle` is enough.)
